local icons = {
    diagnostics = {
        error = " ",
        warning = " ",
        hint = "󰌶 ",
        info = " ",
    },
    lsp_type = {
        Text = "🔤",
        Method = "🧰",
        Function = "🛠️",
        Constructor = "🏗️",
        Field = "🏷️",
        Variable = "📊",
        Class = "📚",
        Interface = "🖥️",
        Module = "📦",
        Property = "🏷️",
        Unit = "📏",
        Value = "🔢",
        Enum = "🆔",
        Keyword = "🔑",
        Snippet = "🧩",
        Color = "🎨",
        File = "📄",
        Reference = "🗃️",
        Folder = "📂",
        EnumMember = "🆔",
        Constant = "💎",
        Struct = "🧱",
        Event = "✨",
        Operator = "➗",
        TypeParameter = " ",
    },
    config = {
        find_file = " ",
        explorer = "פּ ",
        new_file = " ",
        recent_files = " ",
        find_text = " ",
        settings = "漣",
        update = " ",
        exit = " ",
    },
}
